In [1]:
import numpy as np

In [2]:
a=np.array(9)


In [3]:
print(a)

9


In [4]:
print("Add",a + 3)

Add 12


In [5]:
#Vectore(1-D array)
vec=np.array([1,2,3,4,5,6])
print(vec)

[1 2 3 4 5 6]


In [6]:
vec*3

array([ 3,  6,  9, 12, 15, 18])

In [7]:
print(vec + 15)

[16 17 18 19 20 21]


In [8]:
print(vec - vec)

[0 0 0 0 0 0]


In [10]:
#Vectrix (2-D Array) Rows & Columns
mat=np.array([[1,2,3],[1,5,6]])
print(mat)

[[1 2 3]
 [1 5 6]]


In [11]:
mat + 1

array([[2, 3, 4],
       [2, 6, 7]])

In [12]:
mat * 2

array([[ 2,  4,  6],
       [ 2, 10, 12]])

In [13]:
print(mat + 3)

[[4 5 6]
 [4 8 9]]


In [14]:
Mat1=np.array([[1,2],[3,4]])
Mat2=np.array([[5,6],[7,8]])

In [15]:
Mat1

array([[1, 2],
       [3, 4]])

In [16]:
Mat2

array([[5, 6],
       [7, 8]])

In [17]:
Mat1+Mat2

array([[ 6,  8],
       [10, 12]])

In [18]:
Mat1 * Mat2

array([[ 5, 12],
       [21, 32]])

In [19]:
Mat1.shape

(2, 2)

In [20]:
#Transpose a Matrix
Mat1.T

array([[1, 3],
       [2, 4]])

In [22]:
#Determint
A=np.array([[1,2],[3,4]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [25]:
det=np.linalg.det(A)
print(det)
det=ad-bc

-2.0000000000000004


NameError: name 'ad' is not defined

In [26]:
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
det=np.linalg.det(B)
print(det)

0.0


In [37]:
#Detarminent Formula
# det=a(ei-fh)-b(di-fg)+c(dh-eg)

In [29]:
#Identity Matrix
Iden=np.eye(3)
print(Iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#Digonal Matrix

diag=np.diag([1,5,9])
print(diag)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [35]:
#Linear Equation
A=np.array([[4,5,3],
            [4,1,6],
            [9,8,9]
           ])
 ay([6,8,9])

In [36]:
#Solve Linear Equation
X=np.linalg.solve(A, B)
print(X)

[-53.          24.          32.66666667]
