In [19]:
import numpy as np

In [20]:
marks=np.array([[80,90,np.nan],
                [60,np.nan,70],
                [90,85,88],
                [np.nan,55,60],
                [75,np.nan,np.nan]])

In [21]:
marks

array([[80., 90., nan],
       [60., nan, 70.],
       [90., 85., 88.],
       [nan, 55., 60.],
       [75., nan, nan]])

In [22]:
#Replace NaN with student-wise mean
upd_marks=np.nanmean(marks,axis=1)

In [23]:
upd_marks

array([85.        , 65.        , 87.66666667, 57.5       , 75.        ])

In [24]:
filled_marks=np.where(np.isnan(marks),upd_marks[:,np.newaxis],marks)

In [25]:
filled_marks

array([[80. , 90. , 85. ],
       [60. , 65. , 70. ],
       [90. , 85. , 88. ],
       [57.5, 55. , 60. ],
       [75. , 75. , 75. ]])

In [26]:
#Perform SVD
U,S,VT=np.linalg.svd(filled_marks,full_matrices=False)

In [27]:
U

array([[-0.50746089,  0.64187378,  0.4644688 ],
       [-0.38826748,  0.37729773, -0.74740958],
       [-0.52307682, -0.58782083,  0.13616222],
       [-0.34321993, -0.27426955, -0.37841196],
       [-0.44757404, -0.15775725,  0.25280803]])

In [28]:
#Reconstruct approximate marks matrix
k = 2 #it will keep the top 2 most importent marks pattern
U_k =U[:, :k]  # Most important students pattern
S_k = np.diag(S[:k])   #how much is the strength of the pattern
VT_k = VT[:k, :]   #Most important subject in the dataset

approx_marks = U_k @ S_k @ VT_k  # Contruct the matrix with most imp features

In [29]:
approx_marks

array([[79.17814905, 88.63339268, 87.13686458],
       [61.32249846, 67.19910444, 66.56142014],
       [89.75906875, 84.59936968, 88.62643652],
       [58.16957831, 56.11340215, 58.25905394],
       [74.55267067, 74.25616252, 76.16308462]])