In [1]:
import numpy as np
import pandas as pd

In [23]:
# Assuming 'df' is your DataFrame with the given data
df = pd.DataFrame({
    'Student': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'Python': [5, 4, np.nan, 2, 3],
    'Data Science': [4, np.nan, 5, 3, np.nan],
    'ML': [np.nan, 5, 4, np.nan, 2],
    'Web Dev': [2, 3, np.nan, 5, 4],
    'Cloud': [np.nan, 2, 3, 4, np.nan]
}).set_index('Student')

In [24]:
print(df)

         Python  Data Science   ML  Web Dev  Cloud
Student                                           
S1          5.0           4.0  NaN      2.0    NaN
S2          4.0           NaN  5.0      3.0    2.0
S3          NaN           5.0  4.0      NaN    3.0
S4          2.0           3.0  NaN      5.0    4.0
S5          3.0           NaN  2.0      4.0    NaN


In [43]:
# Replace NaN with 0 (or mean/median if needed)
marks_matrix = df.fillna(0).values

In [44]:
# Perform SVD
U, S, VT = np.linalg.svd(marks_matrix, full_matrices=False)

In [45]:
# Choose k=2
k = 2
U_k = U[:, :k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

In [46]:
# Reconstruct approximate marks matrix
approx_marks = U_k @ S_k @ VT_k

In [47]:
print(approx_marks)

[[3.10072326 1.82019571 1.96612833 3.10950175 1.59409653]
 [3.98245711 1.72686549 2.19096065 3.96524273 1.64410585]
 [0.02320693 5.27365589 2.89269296 0.2685616  3.48425512]
 [3.16281526 2.83428338 2.54040567 3.21735935 2.27139015]
 [3.62854104 0.11012207 1.19563326 3.54461998 0.53203658]]
